### ISSUE TITLE
Better Mouse UI

### ISSUE THREAD

**Issue by LordGrimmauld** [imgurbot12/rmenu#10]
Two improvements for mouse UI would be very appreciated:
- currently, any interaction via mouse requires the user to double click any button. This feels weird, since single click just dows nothing. Having things react to single click instead would be nice.
- the mouse cursor will switch to text selection cursor (I-Beam cursor) while hovering over buttons. I understand rmenu is purely text-based in everything but drun which shows icons (where the mouse pointer stays normal while hovering icons). But even if text based, it is still buttons so overriding the cursor type to a standard "finger" or "pointer" cursor would feel more natural.

I know these are possible in Qt, but i am too unfamiliar with gtk to do it myself so this is a feature request "issue" for now until i learn more gtk and rust.

**Comment by imgurbot12** [comment]
Sure, sound easy enough to implement. 

The double click is a bit of a carry-over from the simple list style run menu that used to be the default design for the desktop menu as well. I wanted to be sure people knew what they were clicking since lots of items were stacked fairly close together, so I don't want to completely remove the option to remain double-click but I can easily make it another configuration option with the default set to a single click.

I think i can do the icon thing with CSS but I've never tried that before, will have to experiment but it sounds doable.

Thanks for the suggestions :)

**Comment by imgurbot12** [comment]
@LordGrimmauld, I made a new branch and PR if you'd like to test the changes before I push into master. lmk if you think any other tweaks would be nice.

PR: https://github.com/imgurbot12/rmenu/pull/11
Branch: https://github.com/imgurbot12/rmenu/tree/feat/mouse-tweaks

**Comment by imgurbot12** [comment]
should I update the version of the nix flake as well from `v1.2.0` to `v1.2.1`? not sure if thats required.

**Comment by LordGrimmauld** [comment]
> should I update the version of the nix flake as well from `v1.2.0` to `v1.2.1`? not sure if thats required.

Probably yes. That would make most sense, though the version in the nix flake really isn't all that important beyond recognizing the different versions present in nix store from an ls/grep or doing advanced stuff. Though i might put up another PR doing that as well as clarifying some nix things in the readme.

**Comment by imgurbot12** [comment]
master branch updated with https://github.com/imgurbot12/rmenu/pull/11 closed.
updated the nix version to `v1.2.1` and created a tag with the same name
