### ISSUE TITLE
expected input format ?

### ISSUE THREAD

**Issue by teto** [imgurbot12/rmenu#8]
I am trying this with the nix package but I have no plugin. I tried to pipe newlines on stdin but apparently rmenu is expecting json. 
I searched for an example in the repo but couldn't find a test folder or CI with such a json. Would be nice to have a plugin-less example in README, a command one could just copy/paste.

**Comment by LordGrimmauld** [comment]
The nix package has just been merged and will take a while to hit unstable. Currently the flake based package is on outdated tooling in this repo, with an ongoing PR to fix it. In the meantime you can use the flake in my fork via `nix run github:LordGrimmauld/rmenu -- -r drun` to have a play with it.

**Comment by imgurbot12** [comment]
@teto at the moment rmenu supports json or a dmenu style plaintext format separated by newlines. you can test this out using something like:
```bash
printf 'a\nb\nc' | rmenu -f dmenu
```
otherwise it expects jsons that can built more easily using the cli-tool rmenu-build which is convenient for constructing the proper metadata enriched json-formats more easily than jq

plugins act the same as if they were piped into rmenu with the bonus that you can predefine options for rmenu that will always be set by default when calling the plugin. you can take a look at some of the plugins written in shell to see how to use rmenu-build to generate a custom menu easily
https://github.com/imgurbot12/rmenu/tree/master/other-plugins

**Comment by LordGrimmauld** [comment]
And about that PR: #7 was just merged, so the flake from this repo should just work again using `nix run github:imgurbot12/rmenu -- -r drun`, as the merge updated the wrapper making it automatically find the default config without  hacks. That means all the default plugins will be found too.

**Comment by imgurbot12** [comment]
I just updated the readme to hopefully make things a bit clearer and provide some better examples

**Comment by teto** [comment]
great ty
